spring.application.name=touristy


# elasticsearch configuration
spring.elasticsearch.uris=http://localhost:9200
spring.elasticsearch.username=elastic
spring.elasticsearch.password=Ob4TMC-pI441GBmrh7H6
